[service.file_worker]
module = "../target/wasm32-wasmer-wasi/debug/file-worker.wasm"
env = { LOG_LEVEL = "info" }
mounts = { "./data" = "/data" }

[service.text_api]
module = "../target/wasm32-wasmer-wasi/debug/text-api.wasm"
env = { LISTEN_ADDR = "127.0.0.1:8787" }
network = { listen = "127.0.0.1:8787" }
